#!/bin/bash

TESTS_DIR='tests/'


clear_trash(){
    local trash='.pytest_cache'
    [[ -d "$trash" ]] && echo "removing ${trash} testing trash" && rm -rf ${trash} && echo "environment is cleared"
}


function smoke {
    pytest -m smoke ${TESTS_DIR}
}


function unittest {
    pytest -m unittest ${TESTS_DIR}
}


function all {
    pytest tests/
}


function run_tests {
    local input="$1"
    [[ "${input}" == "all" ]] && all
    [[ "${input}" == "smoke" ]] && smoke
    [[ $# == 0 ]] && echo 'Please use either "unittests", "smoke" or "all" parameters to run tests!' && exit 1
    clear_trash
}

run_tests $1
